### ISSUE TITLE
符号找不到啊

### ISSUE THREAD

**Issue by iOSyifeng** [HuolalaTech/HLLOfflineWebVC-iOS#7]
ld: Undefined symbols:
  _OBJC_CLASS_$_HLLOfflineWebConfig, referenced from:
       in HLLViewController.o
  _OBJC_CLASS_$_HLLOfflineWebPackage, referenced from:
       in HLLViewController.o
  _OBJC_CLASS_$_HLLOfflineWebVC, referenced from:
      _OBJC_CLASS_$_HLLBisnessWebVC in HLLBisnessWebVC.o
  _OBJC_METACLASS_$_HLLOfflineWebVC, referenced from:
      _OBJC_METACLASS_$_HLLBisnessWebVC in HLLBisnessWebVC.o
  _kHLLOfflineWebConfigKey_predownloadList, referenced from:
      -[HLLViewController initOfflineWeb] in HLLViewController.o
      -[HLLViewController preDownloadOfflineWeb] in HLLViewController.o
  _kHLLOfflineWebConfigKey_switch, referenced from:
      -[HLLViewController initOfflineWeb] in HLLViewController.o
      -[HLLViewController preDownloadOfflineWeb] in HLLViewController.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ZYHB** [comment]
修改下podspec文件，Xcode15上运行成功
![image](https://github.com/HuolalaTech/HLLOfflineWebVC-iOS/assets/20578492/330c2dec-ce14-4686-a1d8-8f9aa5442620)

**Comment by binghan-iOS** [comment]
先输入pod install 安装依赖库，再编译。看起来是没有输入这个命令安装依赖库导致的编译错误。本人用xcode 15.2 测试编译是没有问题的
